#!/bin/bash

echo "🚀 BROKER CONNECTOR - SESSION STARTER"
echo "======================================"
echo ""
echo "📋 COPY THIS INTO YOUR NEXT AI SESSION:"
echo ""
echo "---"
echo "PROJECT CONTEXT:"
echo "Spring Boot REST API that can connect to Kite trading platform."
echo "Currently using MCP (Model Context Protocol) client architecture."
echo ""
echo "ARCHITECTURE CLARIFICATION:"
echo "- We're building a Spring Boot REST API (not an MCP server)"
echo "- We use Spring AI's MCP client to communicate with MCP servers"
echo "- Kite/Zerodha provides Kite Connect API (not MCP server)"
echo "- We need an MCP server that bridges our app ↔ Kite API"
echo ""
echo "KEY FILES TO REFERENCE:"
echo "- LEARNING.md (comprehensive learnings & best practices)"
echo "- PROJECT_SUMMARY.md (quick reference)"
echo "- src/main/resources/openapi.yaml (API contract - contract-first approach)"
echo "- src/main/java/com/invom/brokerconnector/controller/KiteBrokerController.java"
echo "- src/main/java/com/invom/brokerconnector/service/KiteBrokerService.java"
echo "- src/main/java/com/invom/brokerconnector/ai/KiteMcpService.java"
echo ""
echo "ARCHITECTURE DECISIONS:"
echo "- External OpenAPI YAML (no annotations in controllers)"
echo "- Clean controllers (only HTTP handling, delegate to services)"
echo "- Service layer for all business logic"
echo "- AI service layer for MCP integration"
echo "- Mock implementations for development when MCP server unavailable"
echo "- Global exception handling with @RestControllerAdvice"
echo "- Standard Spring Boot package structure: com.invom.brokerconnector"
echo ""
echo "PACKAGE STRUCTURE:"
echo "- com.invom.brokerconnector (main package)"
echo "- com.invom.brokerconnector.controller (REST controllers)"
echo "- com.invom.brokerconnector.service (business logic)"
echo "- com.invom.brokerconnector.ai (Spring AI services)"
echo "- com.invom.brokerconnector.dto (request/response models)"
echo "- com.invom.brokerconnector.domain (domain models)"
echo "- com.invom.brokerconnector.config (configuration)"
echo "- com.invom.brokerconnector.exception (global exception handling)"
echo "- com.invom.brokerconnector.util (utilities)"
echo ""
echo "API ENDPOINTS:"
echo "- POST /api/v1/kite/orders (place order)"
echo "- DELETE /api/v1/kite/orders/{orderId} (cancel order)"
echo "- GET /api/v1/kite/positions (get positions)"
echo "- GET /api/v1/kite/holdings (get holdings)"
echo "- GET /api/v1/kite/health (health check)"
echo "- GET /api/v1/kite/connection-test (test MCP server connection)"
echo ""
echo "CURRENT STATUS:"
echo "- ✅ Spring Boot REST API working"
echo "- ✅ MCP client configured"
echo "- ✅ Connection test endpoint working"
echo "- ❌ Need actual MCP server implementation"
echo "- ❌ Need Kite API integration"
echo ""
echo "KEY LEARNINGS FROM LEARNING.md:"
echo "- MCP: Standard protocol for AI-tool communication"
echo "- Architecture: Our app ↔ MCP Server ↔ Kite API"
echo "- Spring AI: Use spring-ai-starter-mcp-client for MCP integration"
echo "- OpenAPI: External YAML keeps code clean, enables code generation"
echo "- Clean Code: Meaningful names, single responsibility, no business logic in controllers"
echo "- Validation: Use @Valid with DTOs, global exception handling"
echo "- Testing: Mock implementations for external dependencies"
echo ""
echo "TECH STACK:"
echo "- Spring Boot 3.5.3, Java 21"
echo "- Spring AI, Spring Web, Spring Validation"
echo "- Lombok, Gradle"
echo "- SpringDoc OpenAPI (contract-first approach)"
echo ""
echo "I acknowledge this project context and our established patterns. Let's proceed with your request."
echo "---"
echo ""
echo "✅ Ready to paste! The AI will acknowledge the context and ask for your specific request." 